project:
  type: website
  output-dir: docs
  
website:
  title: "Forest Quality Pty. Ltd."
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents: 
    - text: "Resistance Drilling"
      href: Resistance-Drilling.qmd
    - section: "NIR analysis"
      href: NIR-Analysis.qmd
      contents:
          - NIR-basics.qmd
    - text: "Data analysis"
      href: Data-Analysis.qmd
  
  navbar:
    collapse: true
    search: true
    logo: ./images/LogoCompact.png
    left:
      - href: index.qmd
        text: "Introduction"
      - About.qmd
  
#href: https://github.com/GeoffDownes/ForestQualityWebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Geoff Downes"

format:
  html:
    theme: ForestQuality.scss
# css: styles.css
    toc: true

editor: visual

