project:
  type: website
  output-dir: docs
  
website:
  title: "Forest Quality Pty. Ltd."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Resistance-Drilling.qmd
      - NIR-Analysis.qmd
      - Data-Analysis.qmd
      - About.qmd

    bibliography: references.bib
  
#href: https://github.com/GeoffDownes/ForestQualityWebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Geoff Downes"

format:
  html:
    theme: ForestQuality.scss
# css: styles.css
    toc: true

editor: visual

