project:
  type: website
  output-dir: docs
  
website:
  title: "Forest Quality"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - href: https://github.com/GeoffDownes/ForestQualityWebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Geoff Downes"

format:
  html:
    theme: ForestQuality.scss
    css: styles.css
    toc: true

editor: source

