project:
  type: website
  output-dir: docs
  
website:
  title: "Forest Quality"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/GeoffDownes/ForestQualityWebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Geoff Downes"

format:
  html:
    theme: minty
    toc: true

editor: source

