---
title: "About us"
bibliography: references.bib
csl: current-forestry-reports.csl
---

<br>

Forestry Quality was established in 2012 as spin-off from the CRC Forestry (<https://www.eoas.info/biogs/A002315b.htm>) which operated from 2005 to 2013. The focus was a Research, Development and Extension company that would take some of the wood quality assessment technology developed within the CRC to continue to provide these to the forest industry. Through many years of working with industry and involvement in non-destructive wood property measurement (SilviScan, near infra red spectroscopy (NIRS), standing tree and log acoustics) the need was still there for an assessment approach that was sufficiently low cost to allow broad-scale, routine application in forest evaluation.

Since its inception, FQ has offered routine NIR analytical services, investing in the establishment of an NIR analytical laboratory utilising well-tested calibrations for the prediction of Kraft pulp yield and cellulose content in plantation eucalypts. Since 2012 we have undertaken the evaluation of over 30 thousand wood meal samples for Australian eucalypt growers and this data has provided an important input into the eucalypt breeding programmes of our industry, as well as providing detailed information on how pulp yield and basic density vary across some of the plantation eucalypt estate.

In 2015 the opportunity arose to explore the application of resistance drilling to the estimation of softwood log quality through relating measurement data to log stiffness (MOE), an important indicator of resultant board properties post log processing. Resistance drilling (IML PD series power drills; RinnTech Resistograph^TM^) allows the measurement of a standing tree with high resolution data describing average wood properties (primarily basic density) and their radial patterns of variation, taking only seconds to sample a tree.

To facilitate its commercial use, we developed a web-based processing platform (e.g <https://forestquality.shinyapps.io/OpenAccess/>) that allowed the drill data to be uploaded, processed and key metrics of growth (over and under bark diameters) and wood properties (basic density and stiffness) to be predicted. This platform allows thousands of traces to be uploaded and processed in a single upload. Data is processed and nothing is stored in the cloud, although the connection to online data bases could be enabled if there was commercial demand.

After multiple studies developing sampling protocols [@RN12] and establishing the accuracy, precision and robustness of the measures (e.g. [@downes2018; @downes2022; @gendvilas2020; @gendvilas2024a; @RN12]), resistance drilling is rapidly establishing itself as a routine commercial operation, contributing to the communication between growers and processors of logs regarding quality attributes based on density and stiffness.

Our IP and software is being utilised by many softwood growers and sawmill processors across Australia, as well as companies in Indonesia, China, South Africa, Brazil and New Zealand.

## Contact

Dr Geoff Downes FIAWS

-   email: geoff.downes\@forestquality.com
-   Postal Address: PO Box 293, Huonville, Tasmaniam 7113, Australia
-   Phone: (+61) 488 023 628
-   https://www.researchgate.net/profile/Geoffrey-Downes
